export type PresetCategory = { key: string; label: string; sort_order: number };
export type PresetItem = {
  name: string;
  category_key: string;
  price_label: string;
  price_num: number | null;
  description: string | null;
  image_url: string | null;
  badge: string | null;
  is_featured: boolean;
  search_key: string | null;
  sort_order: number;
};

export const TAMMMU_PRESET_CATEGORIES: PresetCategory[] = [
  { key: "beverages", label: "Coffee & Drinks", sort_order: 0 },
  { key: "food", label: "Mains & Bites", sort_order: 1 },
  { key: "sourdough", label: "Sourdough Toast", sort_order: 2 },
];

export const TAMMMU_PRESET_ITEMS: PresetItem[] = [
  /* ── BEVERAGES FEATURED (with photo) ── */
  {
    name: "Es Kopi Susu Tammmu",
    category_key: "beverages",
    price_label: "28K",
    price_num: 28000,
    description: "Creamy Coffee with Tammmu Signature Milk",
    image_url: "/tammmu/beverages/Es-Kopi-Susu-Tammmu.png",
    badge: "Bestseller",
    is_featured: true,
    search_key: "es kopi susu tammmu creamy signature milk bestseller coffee",
    sort_order: 0,
  },
  {
    name: "Mont Blanc",
    category_key: "beverages",
    price_label: "39K",
    price_num: 39000,
    description: "Iced coffee topped with delicate velvety citrus cream.",
    image_url: "/tammmu/beverages/Mont-Blanc.png",
    badge: null,
    is_featured: true,
    search_key: "mont blanc signature iced coffee citrus cream",
    sort_order: 1,
  },
  {
    name: "Dirty Latte",
    category_key: "beverages",
    price_label: "38K",
    price_num: 38000,
    description: "Chilled condensed milk with hot double ristretto pull.",
    image_url: "/tammmu/beverages/Dirty-Latte.png",
    badge: null,
    is_featured: true,
    search_key: "dirty latte chilled rich milk double espresso",
    sort_order: 2,
  },
  {
    name: "Cigarettes Fridge",
    category_key: "beverages",
    price_label: "35K",
    price_num: 35000,
    description: "Cola, Vanilla, Coffee, Cream on Top",
    image_url: "/tammmu/beverages/Cigarettes-Fridge.png",
    badge: null,
    is_featured: true,
    search_key: "cigarettes fridge cola vanilla coffee cream cold drink",
    sort_order: 3,
  },
  {
    name: "Tiger Bomb",
    category_key: "beverages",
    price_label: "40K",
    price_num: 40000,
    description: "Bold espresso bomb with tiger stripe layering.",
    image_url: "/tammmu/beverages/Tiger-Bomb.png",
    badge: null,
    is_featured: true,
    search_key: "tiger bomb espresso bold layered signature",
    sort_order: 4,
  },
  {
    name: "Alpenlible",
    category_key: "beverages",
    price_label: "35K",
    price_num: 35000,
    description: "Cranberry, Strawberry, Vanilla, Cream on Top",
    image_url: "/tammmu/beverages/Alpenlible.png",
    badge: null,
    is_featured: true,
    search_key: "alpenlible cranberry strawberry vanilla cream cold drink",
    sort_order: 5,
  },
  {
    name: "Strawberry Matcha",
    category_key: "beverages",
    price_label: "40K",
    price_num: 40000,
    description: "Layered artisan strawberry purée and Uji ceremonial grade matcha.",
    image_url: "/tammmu/beverages/Strawberry-Matcha.png",
    badge: null,
    is_featured: true,
    search_key: "strawberry matcha artisan layered premium ceremonial",
    sort_order: 6,
  },

  /* ── BEVERAGES TEXT ONLY ── */
  {
    name: "Americano (Hot/Ice)",
    category_key: "beverages",
    price_label: "30K",
    price_num: 30000,
    description: "Classic espresso with water.",
    image_url: null,
    badge: null,
    is_featured: false,
    search_key: "americano hot ice espresso classic",
    sort_order: 20,
  },
  {
    name: "Cappuccino (Hot/Ice)",
    category_key: "beverages",
    price_label: "33K",
    price_num: 33000,
    description: "Espresso, steamed milk, silky foam.",
    image_url: null,
    badge: null,
    is_featured: false,
    search_key: "cappuccino hot ice espresso milk foam",
    sort_order: 21,
  },
  {
    name: "Iced Latte",
    category_key: "beverages",
    price_label: "33K",
    price_num: 33000,
    description: "Espresso with cold fresh milk.",
    image_url: null,
    badge: null,
    is_featured: false,
    search_key: "iced latte espresso cold milk",
    sort_order: 22,
  },
  {
    name: "Split Shot",
    category_key: "beverages",
    price_label: "36K",
    price_num: 36000,
    description: "Double shot espresso split.",
    image_url: null,
    badge: null,
    is_featured: false,
    search_key: "split shot double espresso",
    sort_order: 23,
  },
  {
    name: "Magic",
    category_key: "beverages",
    price_label: "36K",
    price_num: 36000,
    description: "Double ristretto with steamed milk.",
    image_url: null,
    badge: null,
    is_featured: false,
    search_key: "magic double ristretto milk",
    sort_order: 24,
  },
  {
    name: "Es Kopi Susu Garen",
    category_key: "beverages",
    price_label: "29K",
    price_num: 29000,
    description: "Signature iced coffee with palm sugar milk.",
    image_url: null,
    badge: null,
    is_featured: false,
    search_key: "es kopi susu garen palm sugar milk iced coffee",
    sort_order: 25,
  },
  {
    name: "Es Kopi Susu Salted Caramel",
    category_key: "beverages",
    price_label: "30K",
    price_num: 30000,
    description: "Iced coffee with salted caramel syrup.",
    image_url: null,
    badge: null,
    is_featured: false,
    search_key: "es kopi susu salted caramel iced coffee",
    sort_order: 26,
  },
  {
    name: "Piccolo",
    category_key: "beverages",
    price_label: "32K",
    price_num: 32000,
    description: "Ristretto shot with steamed milk.",
    image_url: null,
    badge: null,
    is_featured: false,
    search_key: "piccolo ristretto milk",
    sort_order: 27,
  },
  {
    name: "Matcha Latte (Hot/Ice)",
    category_key: "beverages",
    price_label: "33K",
    price_num: 33000,
    description: "Ceremonial grade matcha with fresh milk.",
    image_url: null,
    badge: null,
    is_featured: false,
    search_key: "matcha latte hot ice ceremonial milk",
    sort_order: 28,
  },
  {
    name: "Hot Chocolate (Hot/Ice)",
    category_key: "beverages",
    price_label: "30K",
    price_num: 30000,
    description: "Rich Belgian chocolate with steamed milk.",
    image_url: null,
    badge: null,
    is_featured: false,
    search_key: "hot chocolate belgian milk",
    sort_order: 29,
  },
  {
    name: "Iced Peach Tea",
    category_key: "beverages",
    price_label: "23K",
    price_num: 23000,
    description: "Refreshing peach iced tea.",
    image_url: null,
    badge: null,
    is_featured: false,
    search_key: "iced peach tea refreshing",
    sort_order: 30,
  },
  {
    name: "Iced Berry Lychee Tea",
    category_key: "beverages",
    price_label: "25K",
    price_num: 25000,
    description: "Mixed berry and lychee iced tea.",
    image_url: null,
    badge: null,
    is_featured: false,
    search_key: "iced berry lychee tea mixed",
    sort_order: 31,
  },

  /* ── FOOD FEATURED (with photo) ── */
  {
    name: "Chicken Sambal Matah",
    category_key: "food",
    price_label: "38K",
    price_num: 38000,
    description: "Fried rice with breast chicken and sambal matah TAMMMU signature.",
    image_url: "/tammmu/food/Chicken-Sambal-Matah.png",
    badge: null,
    is_featured: true,
    search_key: "chicken sambal matah fried rice breast fresh balinese",
    sort_order: 0,
  },
  {
    name: "Chicken Sambel Embe",
    category_key: "food",
    price_label: "39K",
    price_num: 39000,
    description: "Fried rice with breast chicken and sambal embe TAMMMU signature.",
    image_url: "/tammmu/food/Chicken-Sambel-Embe.png",
    badge: null,
    is_featured: true,
    search_key: "chicken sambel embe fried rice breast",
    sort_order: 1,
  },
  {
    name: "Chicken Skin",
    category_key: "food",
    price_label: "35K",
    price_num: 35000,
    description: "Crispy Chicken Skin with Aioli Sauce.",
    image_url: "/tammmu/food/Chicken-Skin.png",
    badge: null,
    is_featured: true,
    search_key: "chicken skin crispy aioli sauce",
    sort_order: 2,
  },
  {
    name: "Chicken Wings",
    category_key: "food",
    price_label: "42K",
    price_num: 42000,
    description: "Wings Signature Rub, TAMMMU's Signature Truffle Oil.",
    image_url: "/tammmu/food/Chicken-Wings.png",
    badge: null,
    is_featured: true,
    search_key: "chicken wings signature rub truffle oil",
    sort_order: 3,
  },
  {
    name: "Truffle Fries with Aioli",
    category_key: "food",
    price_label: "38K",
    price_num: 38000,
    description: "Crispy shoestring fries, grated parmesan, and fragrant truffle oil.",
    image_url: "/tammmu/food/Truffle-Fries-with-Aioli.png",
    badge: null,
    is_featured: true,
    search_key: "truffle fries aioli parmesan truffle oil",
    sort_order: 4,
  },
  {
    name: "Spaghetti Carbonara con Manzo",
    category_key: "food",
    price_label: "43K",
    price_num: 43000,
    description: "Spaghetti with cheese and beef.",
    image_url: "/tammmu/food/Spaghetti-Carbonara-con-Manzo.png",
    badge: null,
    is_featured: true,
    search_key: "spaghetti carbonara con manzo cheese beef pasta",
    sort_order: 5,
  },
  {
    name: "Nasi Goreng Brisket",
    category_key: "food",
    price_label: "40K",
    price_num: 40000,
    description: "Fried rice with homemade brisket beef.",
    image_url: "/tammmu/food/Nasi-Goreng-Brisket.png",
    badge: null,
    is_featured: true,
    search_key: "nasi goreng brisket fried rice homemade beef",
    sort_order: 6,
  },

  /* ── FOOD TEXT-ONLY ── */
  {
    name: "Truffle Parmesan Fries",
    category_key: "food",
    price_label: "38K",
    price_num: 38000,
    description: "Fries, Parmesan Cheese, Truffle Oil.",
    image_url: null,
    badge: null,
    is_featured: false,
    search_key: "truffle parmesan fries cheese oil",
    sort_order: 20,
  },
  {
    name: "Spaghetti Aglio e' Olio con Manzo",
    category_key: "food",
    price_label: "39K",
    price_num: 39000,
    description: "Spaghetti with garlic confit and Italian herbs.",
    image_url: null,
    badge: null,
    is_featured: false,
    search_key: "spaghetti aglio olio con manzo garlic confit italian herbs pasta",
    sort_order: 21,
  },

  /* ── SOURDOUGH FEATURED ── */
  {
    name: "Sourdough Tre Formaggio",
    category_key: "sourdough",
    price_label: "48K",
    price_num: 48000,
    description: "Sourdough, Triple Cheese, Aioli Sauce.",
    image_url: "/tammmu/food/Sourdough-Tre-Formaggio.png",
    badge: null,
    is_featured: true,
    search_key: "sourdough tre formaggio triple cheese aioli sauce",
    sort_order: 0,
  },
  {
    name: "Sourdough Mafioso",
    category_key: "sourdough",
    price_label: "48K",
    price_num: 48000,
    description: "Sourdough, Brisket Beef, Mozzarella, Aioli Sauce.",
    image_url: "/tammmu/food/Sourdough-Mafioso.png",
    badge: null,
    is_featured: true,
    search_key: "sourdough mafioso brisket beef mozzarella aioli",
    sort_order: 1,
  },
];

export function countTammmuPresets() {
  return {
    categories: TAMMMU_PRESET_CATEGORIES.length,
    items: TAMMMU_PRESET_ITEMS.length,
  };
}
